# Generated by Django 4.2 on 2026-01-02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0002_add_profile_address_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unavailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailabilities",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddConstraint(
            model_name="unavailability",
            constraint=models.UniqueConstraint(fields=("volunteer", "date"), name="unique_unavailability_per_day"),
        ),
    ]
